baseurl: https://qbiodiversity.netlify.app/
languageCode: en-us
title: Quantitative Biodiversity
theme: blackburn
author: CK
copyright: '&copy; 2024. All rights reserved.'
canonifyurls: yes
pagination:
  pagerSize: 10
indexes:
  tag: tags
  topic: topics
params:
  brand: QB
  dateFormat: 02 Jan 2006, 15:04
  subtitle: BIOL Z620
  social:
    github: QuantitativeBiodiversity

menu:
  main:
    - identifier: summary
      name: Summary
      pre: <i class='fa fa-home fa-fw'></i>
      url: /summary
      weight: 1
    - identifier: objectives
      name: Objectives
      pre: <i class='fa fa-list fa-fw'></i>
      url: /objectives
      weight: 2
    - identifier: resources
      name: Resources
      pre: <i class='fa fa-info fa-fw'></i>
      url: /resources
      weight: 3
    - identifier: schedule
      name: Schedule
      pre: <i class='fa fa-calendar fa-fw'></i>
      url: /schedule
      weight: 4
    - identifier: contact
      name: Contact
      pre: <i class='fa fa-user fa-fw'></i>
      url: /contact
      weight: 5
      
markup:
  goldmark:
    renderer:
      unsafe: true
